options:
  logging: CLOUD_LOGGING_ONLY
steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app', '.']

  # Step 2: Push the image to Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-app']

  # Step 3: Deploy the image to GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/flask-app-deployment'
      - 'flask-app=gcr.io/$PROJECT_ID/flask-app'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=my-gke-cluster'

substitutions:
  PROJECT_ID: mimetic-coral-436411-t1

images:
  - 'gcr.io/$PROJECT_ID/flask-app'

